"""Generador de script Playwright para el paso 1 de identificación PQRSD (Alcaldía de Medellín).

El código generado se ejecuta dentro del contenedor browser (Strix); los valores vienen validados
vía Pydantic en la skill, no del LLM en bruto.
"""

from __future__ import annotations

import json
import re


def _lit_json(obj: object) -> str:
    """Literal JSON seguro para incrustar en el script generado."""
    return json.dumps(obj, ensure_ascii=False)


def build_pqrsd_identificacion_playwright_script(
    *,
    modo: str,
    tipo_documento: str | None,
    numero_documento: str | None,
    correo: str | None,
    correo_confirmacion: str | None,
) -> str:
    """Devuelve el cuerpo del `python -c` ejecutado en el sandbox browser."""
    m = (modo or "").strip()
    if m not in ("identificada", "anonima"):
        raise ValueError("modo debe ser identificada o anonima")
    modo_j = _lit_json(m)
    tipo_j = _lit_json((tipo_documento or "").strip())
    num_j = _lit_json((numero_documento or "").strip())
    em_j = _lit_json((correo or "").strip())
    em2_j = _lit_json((correo_confirmacion or "").strip())

    lines: list[str] = [
        "import asyncio",
        "import json",
        "import os",
        "import re",
        "import shutil",
        "import subprocess",
        "import sys",
        "import time",
        "from playwright.async_api import async_playwright",
        "",
        "_SHOW_PROFILE = '/workspace/chrome_vnc_show'",
        "PQ_URL = 'https://www.medellin.gov.co/es/pqrsd/'",
        f"MODO = {modo_j}",
        f"TIPO_DOC = {tipo_j}",
        f"NUM_DOC = {num_j}",
        f"EMAIL = {em_j}",
        f"EMAIL2 = {em2_j}",
        "",
        "def _spawn_visible_chromium(open_url: str) -> None:",
        "    exe = shutil.which('chromium') or shutil.which('chromium-browser')",
        "    if not exe:",
        "        exe = '/usr/bin/chromium'",
        "    if not os.path.isfile(exe):",
        "        return",
        "    subprocess.run(",
        "        ['pkill', '-f', _SHOW_PROFILE],",
        "        stdout=subprocess.DEVNULL,",
        "        stderr=subprocess.DEVNULL,",
        "    )",
        "    time.sleep(0.35)",
        "    subprocess.Popen(",
        "        [exe, '--no-sandbox', '--disable-dev-shm-usage', '--user-data-dir', _SHOW_PROFILE, open_url],",
        "        env={**os.environ, 'DISPLAY': os.environ.get('DISPLAY', ':99')},",
        "        start_new_session=True,",
        "        stdout=subprocess.DEVNULL,",
        "        stderr=subprocess.DEVNULL,",
        "    )",
        "",
        "def _out(payload: dict) -> None:",
        "    print(json.dumps(payload, ensure_ascii=False))",
        "    sys.stdout.flush()",
        "",
        "async def _scroll_page(page):",
        "    for y in (0, 400, 900, 1400, 2200, 3200, 4200):",
        '        await page.evaluate("(y) => window.scrollTo(0, y)", y)',
        "        await page.wait_for_timeout(350)",
        "",
        "async def _scroll_ctx(page, ctx) -> None:",
        "    \"\"\"Scroll dentro de Page o FrameLocator (Mercurio va en iframe).\"\"\"",
        "    for y in (0, 400, 900, 1400, 2200, 3200, 4200):",
        "        try:",
        "            await ctx.locator('body').first.evaluate(",
        "                '(y) => { window.scrollTo(0, y); document.documentElement.scrollTop = y; }',",
        "                y,",
        "            )",
        "        except Exception:",
        "            try:",
        '                await page.evaluate("(y) => window.scrollTo(0, y)", y)',
        "            except Exception:",
        "                pass",
        "        await page.wait_for_timeout(350)",
        "",
        "async def _mercurio_frame(page):",
        "    \"\"\"El formulario PQRSD está en iframe #iframe-pqrs → mercurio.medellin.gov.co (no en el DOM padre).\"\"\"",
        "    await _scroll_page(page)",
        "    await page.locator('#iframe-pqrs').first.wait_for(state='attached', timeout=120000)",
        "    for _ in range(90):",
        "        src = await page.locator('#iframe-pqrs').first.get_attribute('src') or ''",
        "        if 'mercurio' in src.lower() and 'about:blank' not in src.lower():",
        "            break",
        "        await page.wait_for_timeout(1000)",
        "    fr = page.frame_locator('#iframe-pqrs')",
        "    await fr.locator('body').first.wait_for(state='attached', timeout=120000)",
        "    return fr",
        "",
        "async def _iframe_has_identificacion_step1(fr) -> bool:",
        "    \"\"\"Mercurio (inicialPqr.jsp) ya trae el formulario en el iframe; el botón 'Radicación PQRSD' está en la página padre, no dentro del iframe.\"\"\"",
        "    try:",
        "        if await fr.locator('select[name=\"tipoDocumento\"]').count():",
        "            return True",
        "        if await fr.locator('#correo').count():",
        "            return True",
        "        if await fr.locator('input[name=\"cedula\"]').count():",
        "            return True",
        "    except Exception:",
        "        pass",
        "    return False",
        "",
        "async def _accept_privacy_consent(page) -> None:",
        "    \"\"\"Gov.co suele usar interruptor (role=switch) u overlay de términos antes de habilitar acciones.\"\"\"",
        "    for rx in (",
        "        re.compile(r't[eé]rminos', re.I),",
        "        re.compile(r'privacidad', re.I),",
        "        re.compile(r'Acepta', re.I),",
        "    ):",
        "        try:",
        "            sw = page.get_by_role('switch', name=rx)",
        "            if await sw.count():",
        "                el = sw.first",
        "                if await el.is_visible():",
        "                    aria = await el.get_attribute('aria-checked')",
        "                    if aria != 'true':",
        "                        await el.click(timeout=12000)",
        "                    return",
        "        except Exception:",
        "            pass",
        "    try:",
        "        sw_all = page.get_by_role('switch')",
        "        n = await sw_all.count()",
        "        for i in range(min(n, 12)):",
        "            el = sw_all.nth(i)",
        "            if not await el.is_visible():",
        "                continue",
        "            aria = await el.get_attribute('aria-checked')",
        "            if aria == 'true':",
        "                continue",
        "            txt = (await el.text_content() or '') + ' ' + (await el.get_attribute('aria-label') or '')",
        "            if re.search(r't[eé]rminos|privacidad|Acepta', txt, re.I):",
        "                await el.click(timeout=12000)",
        "                return",
        "    except Exception:",
        "        pass",
        "    for loc in (page.get_by_role('checkbox'), page.locator('input[type=checkbox]')):",
        "        try:",
        "            n = await loc.count()",
        "            for i in range(min(n, 12)):",
        "                el = loc.nth(i)",
        "                if await el.is_visible():",
        "                    await el.check(timeout=8000)",
        "                    return",
        "        except Exception:",
        "            continue",
        "    try:",
        "        lbl = page.get_by_text(re.compile(r'Acepta\\s+.*t[eé]rminos', re.I)).first",
        "        if await lbl.is_visible():",
        "            await lbl.click(timeout=8000)",
        "    except Exception:",
        "        pass",
        "",
        "async def _click_radicacion(ctx, page, anonima: bool) -> None:",
        "    rx_anon = re.compile(r'Radicaci[oó]n.*PQRSD.*an[oó]nima', re.I)",
        "    rx_id = re.compile(r'Radicaci[oó]n\\s+PQRSD(?!.*an[oó]nima)', re.I)",
        "    pat = rx_anon if anonima else rx_id",
        "    last_err = None",
        "    for attempt in range(4):",
        "        await _scroll_ctx(page, ctx)",
        "        await page.wait_for_timeout(500)",
        "        try:",
        "            for role in ('button', 'link'):",
        "                loc = ctx.get_by_role(role, name=pat)",
        "                if await loc.count():",
        "                    await loc.first.click(timeout=25000)",
        "                    return",
        "            wide = ctx.locator(",
        "                'a, button, [role=\"button\"], [role=\"link\"], div[role=\"button\"]'",
        "            ).filter(has_text=pat)",
        "            if await wide.count():",
        "                await wide.first.click(timeout=25000)",
        "                return",
        "            tloc = ctx.get_by_text(pat)",
        "            if await tloc.count():",
        "                await tloc.first.click(timeout=25000)",
        "                return",
        "        except Exception as e:",
        "            last_err = e",
        "        await page.wait_for_timeout(900)",
        "    msg = 'No se encontró el control Radicación PQRSD tras varios intentos'",
        "    if last_err:",
        "        msg += f': {last_err}'",
        "    raise RuntimeError(msg)",
        "",
        "async def _select_option_texts(el):",
        "    try:",
        "        return await el.evaluate(",
        "            '(e) => [...e.options].map(o => String(o.textContent || o.label || \"\").trim()).filter(Boolean)'",
        "        )",
        "    except Exception:",
        "        return []",
        "",
        "async def _select_looks_like_tipo_documento(el) -> bool:",
        "    \"\"\"Evita selects de navegación (p. ej. class=select_secretarias) sin opción de cédula.\"\"\"",
        "    texts = await _select_option_texts(el)",
        "    if not texts:",
        "        return False",
        "    pat = re.compile(",
        "        r'c[eé]dula|pasaporte|tarjeta\\s+de\\s+identidad|extranjer|registro\\s+civil|nit\\b',",
        "        re.I,",
        "    )",
        "    return any(pat.search(t) for t in texts)",
        "",
        "async def _first_visible_form_select(root):",
        "    \"\"\"Primer <select> visible: no Translate, no filtro secretarías; opciones parecen tipo de documento.\"\"\"",
        "    loc = root.locator('select')",
        "    n = await loc.count()",
        "    for i in range(min(n, 40)):",
        "        el = loc.nth(i)",
        "        try:",
        "            if not await el.is_visible():",
        "                continue",
        "        except Exception:",
        "            continue",
        "        cls = (await el.get_attribute('class') or '')",
        "        if 'goog-te-combo' in cls:",
        "            continue",
        "        if 'select_secretarias' in cls:",
        "            continue",
        "        nid = f\"{(await el.get_attribute('id') or '')} {(await el.get_attribute('name') or '')}\"",
        "        if re.search(r'secretar', nid, re.I):",
        "            continue",
        "        al = (await el.get_attribute('aria-label') or '')",
        "        if re.search(r'traducci|translate|idiomas', al, re.I):",
        "            continue",
        "        if re.search(r'secretar', al, re.I):",
        "            continue",
        "        try:",
        "            in_gt = await el.evaluate(",
        "                '(e) => !!(e.closest(\"#google_translate_element\") '",
        "                '|| e.closest(\".goog-te-banner-frame\") '",
        "                '|| e.closest(\".skiptranslate\"))'",
        "            )",
        "        except Exception:",
        "            in_gt = False",
        "        if in_gt:",
        "            continue",
        "        if not await _select_looks_like_tipo_documento(el):",
        "            continue",
        "        return el",
        "    return None",
        "",
        "async def _fill_identificada(fr) -> None:",
        "    if TIPO_DOC:",
        "        picked = False",
        "        try:",
        "            await fr.locator('select[name=\"tipoDocumento\"]').first.select_option(",
        "                label=TIPO_DOC, timeout=30000",
        "            )",
        "            picked = True",
        "        except Exception:",
        "            pass",
        "        if not picked:",
        "            try:",
        "                await fr.get_by_label(re.compile(r'tipo.*documento', re.I)).first.select_option(",
        "                    label=TIPO_DOC, timeout=30000",
        "                )",
        "                picked = True",
        "            except Exception:",
        "                pass",
        "        if not picked:",
        "            el = await _first_visible_form_select(fr)",
        "            if el is None:",
        "                raise RuntimeError(",
        "                    'No se encontró <select> de tipo de documento en el iframe Mercurio (#iframe-pqrs)'",
        "                )",
        "            await el.select_option(label=TIPO_DOC, timeout=30000)",
        "    if NUM_DOC:",
        "        filled = False",
        "        try:",
        "            await fr.locator('input[name=\"cedula\"]').first.fill(NUM_DOC, timeout=15000)",
        "            filled = True",
        "        except Exception:",
        "            pass",
        "        if not filled:",
        "            for rx in (re.compile(r'n[uú]mero', re.I), re.compile(r'documento', re.I)):",
        "                try:",
        "                    await fr.get_by_label(rx).first.fill(NUM_DOC, timeout=15000)",
        "                    filled = True",
        "                    break",
        "                except Exception:",
        "                    continue",
        "        if not filled:",
        "            await fr.locator('input[type=\"text\"]:visible').first.fill(NUM_DOC, timeout=15000)",
        "    if EMAIL:",
        "        try:",
        "            await fr.locator('#correo').first.fill(EMAIL, timeout=15000)",
        "        except Exception:",
        "            try:",
        "                await fr.get_by_label(re.compile(r'correo.*electr[oó]nico', re.I)).first.fill(EMAIL, timeout=15000)",
        "            except Exception:",
        "                await fr.locator('input[type=email]').first.fill(EMAIL, timeout=15000)",
        "    if EMAIL2:",
        "        try:",
        "            await fr.locator('#confirmCorreo').first.fill(EMAIL2, timeout=15000)",
        "        except Exception:",
        "            try:",
        "                await fr.get_by_label(re.compile(r'confirm', re.I)).first.fill(EMAIL2, timeout=15000)",
        "            except Exception:",
        "                n = await fr.locator('input[type=email]').count()",
        "                if n > 1:",
        "                    await fr.locator('input[type=email]').nth(1).fill(EMAIL2, timeout=15000)",
        "",
        "async def _fill_correos_only(fr) -> None:",
        "    if EMAIL:",
        "        try:",
        "            await fr.locator('#correo').first.fill(EMAIL, timeout=15000)",
        "        except Exception:",
        "            try:",
        "                await fr.get_by_label(re.compile(r'correo(?!.*confirm)', re.I)).first.fill(EMAIL, timeout=15000)",
        "            except Exception:",
        "                await fr.locator('input[type=email]').first.fill(EMAIL, timeout=15000)",
        "    if EMAIL2:",
        "        try:",
        "            await fr.locator('#confirmCorreo').first.fill(EMAIL2, timeout=15000)",
        "        except Exception:",
        "            try:",
        "                await fr.get_by_label(re.compile(r'confirm', re.I)).first.fill(EMAIL2, timeout=15000)",
        "            except Exception:",
        "                c = await fr.locator('input[type=email]').count()",
        "                if c > 1:",
        "                    await fr.locator('input[type=email]').nth(1).fill(EMAIL2, timeout=15000)",
        "",
        "async def _accept_terms(page, fr) -> None:",
        "    await _accept_privacy_consent(page)",
        "    try:",
        "        await _accept_privacy_consent(fr)",
        "    except Exception:",
        "        pass",
        "",
        "async def _click_verificacion(ctx, page) -> None:",
        "    rx = re.compile(r'obtener.*verific', re.I)",
        "    for role in ('button', 'link'):",
        "        loc = ctx.get_by_role(role, name=rx)",
        "        if await loc.count():",
        "            await loc.first.click(timeout=60000)",
        "            return",
        "    wide = ctx.locator('a, button, [role=\"button\"]').filter(has_text=rx)",
        "    if await wide.count():",
        "        await wide.first.click(timeout=60000)",
        "        return",
        "    tloc = ctx.get_by_text(rx)",
        "    if await tloc.count():",
        "        await tloc.first.click(timeout=60000)",
        "        return",
        "    raise RuntimeError('No se encontró el botón Obtener número de verificación')",
        "",
        "async def main():",
        "    err = None",
        "    final_url = PQ_URL",
        "    title = ''",
        "    radicacion_path = 'unknown'",
        "    try:",
        "        async with async_playwright() as p:",
        "            browser = await p.chromium.launch_persistent_context(",
        "                user_data_dir=os.environ.get('STRIX_CHROME_PROFILE_DIR', '/workspace/chrome_profile'),",
        "                headless=False,",
        "                args=['--disable-blink-features=AutomationControlled'],",
        "                viewport={'width': 1280, 'height': 720},",
        "            )",
        "            page = await browser.new_page()",
        "            await page.goto(PQ_URL, wait_until='domcontentloaded', timeout=120000)",
        "            await page.wait_for_timeout(2000)",
        "            await _accept_privacy_consent(page)",
        "            fr = await _mercurio_frame(page)",
        "            if await _iframe_has_identificacion_step1(fr):",
        "                radicacion_path = 'iframe_form_ready'",
        "            else:",
        "                await _click_radicacion(page, page, anonima=(MODO == 'anonima'))",
        "                radicacion_path = 'clicked_parent'",
        "                await page.wait_for_timeout(2500)",
        "                fr = page.frame_locator('#iframe-pqrs')",
        "                await fr.locator('body').first.wait_for(state='attached', timeout=120000)",
        "                if not await _iframe_has_identificacion_step1(fr):",
        "                    await _click_radicacion(fr, page, anonima=(MODO == 'anonima'))",
        "                    radicacion_path = 'clicked_iframe_fallback'",
        "                    await page.wait_for_timeout(2000)",
        "            await page.wait_for_timeout(800)",
        "            if MODO == 'identificada':",
        "                await _fill_identificada(fr)",
        "            else:",
        "                await _fill_correos_only(fr)",
        "            await _accept_terms(page, fr)",
        "            await page.wait_for_timeout(600)",
        "            await _click_verificacion(fr, page)",
        "            await page.wait_for_timeout(2000)",
        "            final_url = page.url",
        "            title = await page.title()",
        "            await page.screenshot(path='/workspace/output/pqrsd_identificacion_step1.png', full_page=False)",
        "            await browser.close()",
        "    except Exception as e:",
        "        err = str(e)",
        "    payload = {",
        "        'ok': err is None,",
        "        'step': 'identificacion_solicitar_verificacion',",
        "        'url': final_url,",
        "        'title': title,",
        "        'modo': MODO,",
        "        'mercurio_iframe': True,",
        "        'radicacion_path': radicacion_path,",
        "    }",
        "    if err:",
        "        payload['error'] = err",
        "    _out(payload)",
        "    _spawn_visible_chromium(final_url if final_url else PQ_URL)",
        "",
        "asyncio.run(main())",
        "",
    ]
    return "\n".join(lines)


def normalize_document_number(s: str) -> str:
    return re.sub(r"\s+", "", (s or "").strip())


def emails_match(a: str, b: str) -> bool:
    return (a or "").strip().lower() == (b or "").strip().lower()
