/**
 * PM2 config for DuckClaw Telegram bot (generated by wizard).
 * Start: pm2 start ecosystem.core.config.cjs
 * Stop:  pm2 stop Finanz-Inference
 *
 * Token: guardado en .env (auto-cargado por el bot al iniciar).
 * Para actualizar el token: edita .env o regenera este config desde el wizard.
 */
module.exports = {
  apps: [
    {
      name: "Finanz-Inference",
      script: "/Users/juanjosearevalocamargo/Desktop/duckclaw/.venv/bin/python3",
      args: "-m core.integrations.telegram_bot",
      cwd: "/Users/juanjosearevalocamargo/Desktop/duckclaw",
      interpreter: "none",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      env: {
        PYTHONPATH: "/Users/juanjosearevalocamargo/Desktop/duckclaw",
        DUCKCLAW_DB_PATH: "db/telegram.duckdb",
        DUCKCLAW_BOT_MODE: "langgraph",
        DUCKCLAW_LLM_PROVIDER: "mlx",
        DUCKCLAW_LLM_MODEL: "",
        DUCKCLAW_LLM_BASE_URL: "",
      },
    },
  ],
};
